title:            Can Küçükyılmaz'ın Web Günlüğü
description:      Bir başka web programcısının buldukları...
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Ana Sayfa
    url:          /
  - name:         Hakkında
    url:          /about
  - name:         Github
    url:          https://github.com/defli
    external:     true
  - name:         Linkedin
    url:          https://www.linkedin.com/pub/can-kucukyilmaz/
    external:     true
  - name:         Twitter
    url:          https://twitter.com/cankucukyilmaz
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
