title:            Can Küçükyılmaz'ın Web Günlüğü
description:      Bir başka web programcısının buldukları...
url:              "http://can.kucukyilmaz.org"
signoff:          "Can Küçükyılmaz"
disqus_shortname: defli
facebook_appid:   1393315454317518
google_analytics: UA-60512411-1

links:
  - name:         Ana Sayfa
    url:          /
  - name:         Hakkında
    url:          /about
  - name:         Github
    url:          https://github.com/defli
    external:     true
  - name:         Linkedin
    url:          https://www.linkedin.com/pub/can-kucukyilmaz/
    external:     true
  - name:         Twitter
    url:          https://twitter.com/cankucukyilmaz
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
    - superscript
